# This task run will run using mentioned service account, will not use default
# This YAML should be applied using kubectl create command
# tkn task start <task-name> will generate serviceAccountName="" , so access issue comes
#
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
#  name: deployment-nginx-run
  generateName: deployment-nginx-run-
spec:
  serviceAccountName: service-account
  taskRef:
    name: deployment-nginx-task
  params:
  - name: imageTag
    value: latest
  - name: imageUrl
    value: nginx  
  resources:
    inputs:
      - name: workspace
        resourceRef:
          name: deployment-example-git


# Steps:
# Create service account using service-account.yaml
# kubect create -f deployment-taskrun.yaml