# service-account need to be created before deployment using service-account.yaml

# Pipeline resource for GIT
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: deployment-example-git
spec:
  type: git
  params:
    - name: url
      value: https://github.com/atulchauhan01/kubernetes-yaml-files.git
---
# This task has steps that helps in debug
# It will print all file in workspace folder
# Code to read specific file from the GIT repository
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deployment-nginx
spec:
  resources:
    inputs:
      - name: workspace
        type: git
  steps:
    - name: build-and-push-1
      image: ubuntu
      command:
      - /bin/bash
      args:
      - -c
      - |
        set -ex
        find /workspace  
    - name: readme
      image: ubuntu
      script: cat workspace/tekton/task/nginx-deployment.yaml
    - name: deploy-app
      image: lachlanevenson/k8s-kubectl
      command: ["kubectl"]
      args:
        - "apply"
        - "-f"
        - "workspace/tekton/task/nginx-deployment.yaml"
---
# This task run will run using mentioned service account, will not use default
# This YAML should be applied using kubectl create command
# tkn task start <task-name> will generate serviceAccountName="" , so access issue comes
#
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: deployment-nginx-run
spec:
  status: "TaskRunCancelled"
  serviceAccountName: service-account
  taskRef:
    name: deployment-nginx
  resources:
    inputs:
      - name: workspace
        resourceRef:
          name: deployment-example-git